# Generated by Django 4.2.7 on 2023-12-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_mymodel_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path_field',
        ),
    ]
